[package]
name = "ignis"
description = "The kernel for the Vesper operating system"
authors = ["Vesper development team"]
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]